// Sandbox fallback hotel inventory. Loaded before the Babel app so static data
// does not add to browser-side JSX transpilation cost. Live SerpAPI results remain
// the primary data source; this list is only used when the sandbox API is offline.
window.HOTELS_RAW = [
  // Santa Barbara, CA
  { name: "Ritz-Carlton Bacara", city: "Santa Barbara", region: "California, US", stars: 5, baseRate: 689, url: "https://www.ritzcarlton.com/en/hotels/sbarz-the-ritz-carlton-bacara-santa-barbara/overview/", chain: "marriott", chainPropertyCode: "SBARZ" },
  { name: "Belmond El Encanto", city: "Santa Barbara", region: "California, US", stars: 5, baseRate: 599, url: "https://www.belmond.com/hotels/north-america/usa/santa-barbara/belmond-el-encanto" },
  { name: "Mar Monte Hotel", city: "Santa Barbara", region: "California, US", stars: 4, baseRate: 412, url: "https://www.hyatt.com/unbound-collection/en-US/sbars-mar-monte-hotel", chain: "hyatt", chainPropertyCode: "sbars" },
  { name: "Hotel Californian", city: "Santa Barbara", region: "California, US", stars: 4, baseRate: 349, url: "https://www.hotelcalifornian.com" },
  { name: "Kimpton Canary Hotel", city: "Santa Barbara", region: "California, US", stars: 4, baseRate: 329, url: "https://www.ihg.com/kimpton/hotels/us/en/santa-barbara/sabcn/hoteldetail", chain: "ihg", chainPropertyCode: "SABCN", chainBrandCode: "KI" },
  { name: "Santa Barbara Inn", city: "Santa Barbara", region: "California, US", stars: 3, baseRate: 249, url: "https://www.santabarbarainn.com" },
  // Charleston, SC
  { name: "Belmond Charleston Place", city: "Charleston", region: "South Carolina, US", stars: 5, baseRate: 499, url: "https://www.belmond.com/hotels/north-america/usa/charleston/belmond-charleston-place" },
  { name: "The Spectator Hotel", city: "Charleston", region: "South Carolina, US", stars: 5, baseRate: 429, url: "https://www.thespectatorhotel.com" },
  { name: "Hotel Bennett", city: "Charleston", region: "South Carolina, US", stars: 5, baseRate: 459, url: "https://www.hotelbennett.com" },
  { name: "The Vendue", city: "Charleston", region: "South Carolina, US", stars: 4, baseRate: 299, url: "https://www.thevendue.com" },
  { name: "Harbourview Inn", city: "Charleston", region: "South Carolina, US", stars: 4, baseRate: 269, url: "https://www.harbourviewinn.com" },
  // Austin, TX
  { name: "Four Seasons Austin", city: "Austin", region: "Texas, US", stars: 5, baseRate: 499, url: "https://www.fourseasons.com/austin" },
  { name: "Hotel Saint Cecilia", city: "Austin", region: "Texas, US", stars: 5, baseRate: 549, url: "https://www.hotelsaintcecilia.com" },
  { name: "The Driskill", city: "Austin", region: "Texas, US", stars: 4, baseRate: 299, url: "https://www.hyatt.com/en-US/hotel/texas/the-driskill/ausal", chain: "hyatt", chainPropertyCode: "ausal" },
  { name: "South Congress Hotel", city: "Austin", region: "Texas, US", stars: 4, baseRate: 279, url: "https://www.southcongresshotel.com" },
  { name: "Kimpton Hotel Van Zandt", city: "Austin", region: "Texas, US", stars: 4, baseRate: 249, url: "https://www.ihg.com/kimpton/hotels/us/en/austin/ausvz/hoteldetail", chain: "ihg", chainPropertyCode: "AUSVZ", chainBrandCode: "KI" },
  // Seattle, WA
  { name: "Four Seasons Seattle", city: "Seattle", region: "Washington, US", stars: 5, baseRate: 549, url: "https://www.fourseasons.com/seattle" },
  { name: "The Edgewater Hotel", city: "Seattle", region: "Washington, US", stars: 4, baseRate: 299, url: "https://www.edgewaterhotel.com" },
  { name: "Hotel 1000", city: "Seattle", region: "Washington, US", stars: 4, baseRate: 279, url: "https://www.hotel1000seattle.com" },
  { name: "Lotte Hotel Seattle", city: "Seattle", region: "Washington, US", stars: 5, baseRate: 349, url: "https://www.lottehotel.com/seattle-hotel" },
  { name: "Ace Hotel Seattle", city: "Seattle", region: "Washington, US", stars: 3, baseRate: 179, url: "https://acehotel.com/seattle" },
  // New York City
  { name: "The Plaza", city: "New York", region: "New York, US", stars: 5, baseRate: 899, url: "https://www.theplazany.com" },
  { name: "The Standard High Line", city: "New York", region: "New York, US", stars: 4, baseRate: 399, url: "https://www.standardhotels.com/new-york/properties/high-line" },
  { name: "1 Hotel Brooklyn Bridge", city: "New York", region: "New York, US", stars: 4, baseRate: 379, url: "https://www.1hotels.com/brooklyn-bridge" },
  { name: "The Bowery Hotel", city: "New York", region: "New York, US", stars: 4, baseRate: 449, url: "https://www.theboweryhotel.com" },
  { name: "Pod 51", city: "New York", region: "New York, US", stars: 3, baseRate: 149, url: "https://www.thepodhotel.com/pod-51" },
  // Paris, France
  { name: "Le Meurice", city: "Paris", region: "France", stars: 5, baseRate: 999, url: "https://www.dorchestercollection.com/paris/le-meurice" },
  { name: "Hotel Plaza Athenee", city: "Paris", region: "France", stars: 5, baseRate: 899, url: "https://www.dorchestercollection.com/paris/hotel-plaza-athenee" },
  { name: "Le Marais Boutique", city: "Paris", region: "France", stars: 4, baseRate: 299, url: "https://www.paris-marais.com" },
  { name: "Hotel Fabric", city: "Paris", region: "France", stars: 3, baseRate: 179, url: "https://www.hotelfabric.com" },
  { name: "Generator Paris", city: "Paris", region: "France", stars: 2, baseRate: 69, url: "https://staygenerator.com/hostels/paris" },
  // Tokyo, Japan
  { name: "Park Hyatt Tokyo", city: "Tokyo", region: "Japan", stars: 5, baseRate: 699, url: "https://www.hyatt.com/park-hyatt/en-US/tyoph-park-hyatt-tokyo", chain: "hyatt", chainPropertyCode: "tyoph" },
  { name: "Aman Tokyo", city: "Tokyo", region: "Japan", stars: 5, baseRate: 999, url: "https://www.aman.com/hotels/aman-tokyo" },
  { name: "The Prince Gallery Tokyo", city: "Tokyo", region: "Japan", stars: 5, baseRate: 449, url: "https://www.marriott.com/hotels/travel/tyolc-the-prince-gallery-tokyo-kioicho", chain: "marriott", chainPropertyCode: "TYOLC" },
  { name: "Shinjuku Granbell Hotel", city: "Tokyo", region: "Japan", stars: 3, baseRate: 129, url: "https://www.granbellhotel.jp/en/shinjuku" },
  { name: "UNPLAN Shinjuku", city: "Tokyo", region: "Japan", stars: 2, baseRate: 49, url: "https://unplan.jp" },
  { name: "Westin Tokyo", city: "Tokyo", region: "Japan", stars: 5, baseRate: 449, url: "https://www.marriott.com/hotels/travel/tyowi-the-westin-tokyo", chain: "marriott", chainPropertyCode: "TYOWI" },
  { name: "Sheraton Miyako Hotel Tokyo", city: "Tokyo", region: "Japan", stars: 4, baseRate: 299, url: "https://www.marriott.com/hotels/travel/tyomy-sheraton-miyako-hotel-tokyo", chain: "marriott", chainPropertyCode: "TYOMY" },
  { name: "Hyatt Regency Tokyo", city: "Tokyo", region: "Japan", stars: 4, baseRate: 379, url: "https://www.hyatt.com/hyatt-regency/en-US/tyoty-hyatt-regency-tokyo", chain: "hyatt", chainPropertyCode: "tyoty" },
  { name: "Andaz Tokyo Toranomon Hills", city: "Tokyo", region: "Japan", stars: 5, baseRate: 499, url: "https://www.hyatt.com/andaz/en-US/tyoaz-andaz-tokyo-toranomon-hills", chain: "hyatt", chainPropertyCode: "tyoaz" },
  { name: "InterContinental Tokyo Bay", city: "Tokyo", region: "Japan", stars: 4, baseRate: 399, url: "https://www.ihg.com/intercontinental/hotels/jp/en/tokyo/tyohb/hoteldetail", chain: "ihg", chainPropertyCode: "TYOHB", chainBrandCode: "IC" },
  // London, UK
  { name: "The Savoy", city: "London", region: "United Kingdom", stars: 5, baseRate: 799, url: "https://www.thesavoylondon.com" },
  { name: "Claridge's", city: "London", region: "United Kingdom", stars: 5, baseRate: 899, url: "https://www.claridges.co.uk" },
  { name: "The Hoxton Shoreditch", city: "London", region: "United Kingdom", stars: 4, baseRate: 199, url: "https://thehoxton.com/london/shoreditch" },
  { name: "citizenM Tower of London", city: "London", region: "United Kingdom", stars: 3, baseRate: 149, url: "https://www.citizenm.com/hotels/europe/london/london-tower-of-london-hotel" },
  { name: "Generator London", city: "London", region: "United Kingdom", stars: 2, baseRate: 59, url: "https://staygenerator.com/hostels/london" },
  { name: "London Marriott Hotel County Hall", city: "London", region: "United Kingdom", stars: 4, baseRate: 449, url: "https://www.marriott.com/hotels/travel/lonch-london-marriott-hotel-county-hall", chain: "marriott", chainPropertyCode: "LONCH" },
  { name: "JW Marriott Grosvenor House London", city: "London", region: "United Kingdom", stars: 5, baseRate: 699, url: "https://www.marriott.com/hotels/travel/longh-jw-marriott-grosvenor-house-london", chain: "marriott", chainPropertyCode: "LONGH" },
  { name: "Hyatt Regency London - The Churchill", city: "London", region: "United Kingdom", stars: 5, baseRate: 479, url: "https://www.hyatt.com/hyatt-regency/en-US/lonch-hyatt-regency-london-the-churchill", chain: "hyatt", chainPropertyCode: "lonch" },
  { name: "Andaz London Liverpool Street", city: "London", region: "United Kingdom", stars: 4, baseRate: 389, url: "https://www.hyatt.com/andaz/en-US/longe-andaz-london-liverpool-street", chain: "hyatt", chainPropertyCode: "longe" },
  { name: "InterContinental London Park Lane", city: "London", region: "United Kingdom", stars: 5, baseRate: 549, url: "https://www.ihg.com/intercontinental/hotels/gb/en/london/lonhb/hoteldetail", chain: "ihg", chainPropertyCode: "LONHB", chainBrandCode: "IC" },
  // Limerick, Ireland
  { name: "The Savoy Limerick", city: "Limerick", region: "Ireland", stars: 5, baseRate: 249, url: "https://www.savoylimerick.com" },
  { name: "No. 1 Pery Square", city: "Limerick", region: "Ireland", stars: 4, baseRate: 199, url: "https://www.oneperysquare.com" },
  { name: "The George Limerick", city: "Limerick", region: "Ireland", stars: 4, baseRate: 169, url: "https://www.thegeorgelimerick.com" },
  { name: "Limerick Strand Hotel", city: "Limerick", region: "Ireland", stars: 4, baseRate: 149, url: "https://www.strandlimerick.ie" },
  { name: "Absolute Hotel", city: "Limerick", region: "Ireland", stars: 4, baseRate: 129, url: "https://www.absolutehotel.com" },
  // Rome, Italy
  { name: "Hotel de Russie", city: "Rome", region: "Italy", stars: 5, baseRate: 699, url: "https://www.roccofortehotels.com/hotels-and-resorts/hotel-de-russie/reservations/" },
  { name: "Hotel Eden", city: "Rome", region: "Italy", stars: 5, baseRate: 799, url: "https://www.dorchestercollection.com/rome/hotel-eden" },
  { name: "Hotel Raphael", city: "Rome", region: "Italy", stars: 4, baseRate: 299, url: "https://www.raphaelhotel.com", chain: "synxis", chainPropertyCode: "26074", synxisChainCode: "8565" },
  { name: "Hotel Artemide", city: "Rome", region: "Italy", stars: 4, baseRate: 199, url: "https://www.hotelartemide.it" },
  { name: "The Yellow", city: "Rome", region: "Italy", stars: 2, baseRate: 59, url: "https://www.the-yellow.com" },
  // Barcelona, Spain
  { name: "Hotel Arts Barcelona", city: "Barcelona", region: "Spain", stars: 5, baseRate: 499, url: "https://www.marriott.com/hotels/travel/bcnrz-hotel-arts-barcelona", chain: "marriott", chainPropertyCode: "BCNRZ" },
  { name: "W Barcelona", city: "Barcelona", region: "Spain", stars: 5, baseRate: 449, url: "https://www.marriott.com/hotels/travel/bcnwh-w-barcelona", chain: "marriott", chainPropertyCode: "BCNWH" },
  { name: "Hotel Casa Fuster", city: "Barcelona", region: "Spain", stars: 5, baseRate: 349, url: "https://www.hotelcasafuster.com" },
  { name: "Yurbban Trafalgar Hotel", city: "Barcelona", region: "Spain", stars: 3, baseRate: 149, url: "https://www.yurbban.com" },
  { name: "Generator Barcelona", city: "Barcelona", region: "Spain", stars: 2, baseRate: 49, url: "https://staygenerator.com/hostels/barcelona" },
  // Sydney, Australia
  { name: "Park Hyatt Sydney", city: "Sydney", region: "Australia", stars: 5, baseRate: 799, url: "https://www.hyatt.com/park-hyatt/en-US/sydph-park-hyatt-sydney", chain: "hyatt", chainPropertyCode: "sydph" },
  { name: "Shangri-La Sydney", city: "Sydney", region: "Australia", stars: 5, baseRate: 399, url: "https://www.shangri-la.com/sydney/shangrila" },
  { name: "QT Sydney", city: "Sydney", region: "Australia", stars: 4, baseRate: 249, url: "https://www.qthotels.com/sydney" },
  { name: "Ovolo Woolloomooloo", city: "Sydney", region: "Australia", stars: 4, baseRate: 229, url: "https://ovolohotels.com/ovolo/woolloomooloo" },
  { name: "Wake Up! Sydney", city: "Sydney", region: "Australia", stars: 2, baseRate: 39, url: "https://www.wakeup.com.au" },
  { name: "Sheraton Grand Sydney Hyde Park", city: "Sydney", region: "Australia", stars: 5, baseRate: 349, url: "https://www.marriott.com/hotels/travel/sydsi-sheraton-grand-sydney-hyde-park", chain: "marriott", chainPropertyCode: "SYDSI" },
  { name: "W Sydney", city: "Sydney", region: "Australia", stars: 5, baseRate: 449, url: "https://www.marriott.com/hotels/travel/sydwh-w-sydney", chain: "marriott", chainPropertyCode: "SYDWH" },
  { name: "Hyatt Regency Sydney", city: "Sydney", region: "Australia", stars: 4, baseRate: 329, url: "https://www.hyatt.com/hyatt-regency/en-US/sydrs-hyatt-regency-sydney", chain: "hyatt", chainPropertyCode: "sydrs" },
  { name: "InterContinental Sydney", city: "Sydney", region: "Australia", stars: 5, baseRate: 429, url: "https://www.ihg.com/intercontinental/hotels/au/en/sydney/sydha/hoteldetail", chain: "ihg", chainPropertyCode: "SYDHA", chainBrandCode: "IC" },
  // Cancun, Mexico
  { name: "Nizuc Resort & Spa", city: "Cancun", region: "Mexico", stars: 5, baseRate: 599, url: "https://www.nizuc.com" },
  { name: "Hyatt Zilara Cancun", city: "Cancun", region: "Mexico", stars: 5, baseRate: 499, url: "https://www.hyatt.com/hyatt-ziva/en-US/cunai-hyatt-zilara-cancun", chain: "hyatt", chainPropertyCode: "cunai" },
  { name: "Secrets The Vine Cancun", city: "Cancun", region: "Mexico", stars: 5, baseRate: 399, url: "https://www.amrcollection.com/en/resorts-hotels/secrets/mexico/secrets-the-vine-cancun" },
  { name: "Fiesta Americana Condesa", city: "Cancun", region: "Mexico", stars: 4, baseRate: 199, url: "https://www.fiestamericana.com/en/hotels-resorts/fiesta-americana-condesa-cancun" },
  { name: "Hostel Mundo Joven Cancun", city: "Cancun", region: "Mexico", stars: 2, baseRate: 29, url: "https://www.mundojovenhostels.com" },
  // Dubai, UAE
  { name: "Burj Al Arab", city: "Dubai", region: "UAE", stars: 5, baseRate: 1999, url: "https://www.jumeirah.com/en/stay/dubai/burj-al-arab-jumeirah" },
  { name: "Atlantis The Palm", city: "Dubai", region: "UAE", stars: 5, baseRate: 499, url: "https://www.atlantis.com/dubai" },
  { name: "One&Only The Palm", city: "Dubai", region: "UAE", stars: 5, baseRate: 799, url: "https://www.oneandonlyresorts.com/the-palm" },
  { name: "Rove Downtown", city: "Dubai", region: "UAE", stars: 3, baseRate: 99, url: "https://www.rovehotels.com/hotel/rove-downtown" },
  { name: "Rove La Mer Beach", city: "Dubai", region: "UAE", stars: 3, baseRate: 89, url: "https://www.rovehotels.com/hotel/rove-la-mer-beach" },
  // Bali, Indonesia
  { name: "Four Seasons Bali at Sayan", city: "Bali", region: "Indonesia", stars: 5, baseRate: 699, url: "https://www.fourseasons.com/sayan" },
  { name: "COMO Uma Ubud", city: "Bali", region: "Indonesia", stars: 5, baseRate: 399, url: "https://www.comohotels.com/uma-ubud" },
  { name: "Alila Seminyak", city: "Bali", region: "Indonesia", stars: 5, baseRate: 299, url: "https://www.alilahotels.com/seminyak" },
  { name: "The Oberoi Bali", city: "Bali", region: "Indonesia", stars: 5, baseRate: 349, url: "https://www.oberoihotels.com/hotels-in-bali" },
  { name: "Kuta Beach Hostel", city: "Bali", region: "Indonesia", stars: 2, baseRate: 19, url: "https://www.hostelworld.com/st/hostels/bali" },
  // San Francisco, CA
  { name: "The St. Regis San Francisco", city: "San Francisco", region: "California, US", stars: 5, baseRate: 599, url: "https://www.marriott.com/hotels/travel/sfoxr-the-st-regis-san-francisco", chain: "marriott", chainPropertyCode: "SFOXR" },
  { name: "Hotel Vitale", city: "San Francisco", region: "California, US", stars: 4, baseRate: 329, url: "https://www.1hotels.com/san-francisco" },
  { name: "The Marker San Francisco", city: "San Francisco", region: "California, US", stars: 4, baseRate: 249, url: "https://www.themarkersanfrancisco.com" },
  { name: "Hotel Zetta", city: "San Francisco", region: "California, US", stars: 4, baseRate: 219, url: "https://www.hotelzetta.com" },
  { name: "HI San Francisco Downtown", city: "San Francisco", region: "California, US", stars: 2, baseRate: 49, url: "https://www.hiusa.org/hostels/california/san-francisco/downtown" },
  { name: "San Francisco Marriott Marquis", city: "San Francisco", region: "California, US", stars: 4, baseRate: 329, url: "https://www.marriott.com/hotels/travel/sfodt-san-francisco-marriott-marquis", chain: "marriott", chainPropertyCode: "SFODT" },
  { name: "W San Francisco", city: "San Francisco", region: "California, US", stars: 4, baseRate: 389, url: "https://www.marriott.com/hotels/travel/sfowh-w-san-francisco", chain: "marriott", chainPropertyCode: "SFOWH" },
  { name: "Hyatt Regency San Francisco", city: "San Francisco", region: "California, US", stars: 4, baseRate: 289, url: "https://www.hyatt.com/hyatt-regency/en-US/sfors-hyatt-regency-san-francisco", chain: "hyatt", chainPropertyCode: "sfors" },
  { name: "Grand Hyatt San Francisco", city: "San Francisco", region: "California, US", stars: 4, baseRate: 309, url: "https://www.hyatt.com/grand-hyatt/en-US/sfous-grand-hyatt-san-francisco", chain: "hyatt", chainPropertyCode: "sfous" },
  { name: "Kimpton Alton Hotel Fisherman's Wharf", city: "San Francisco", region: "California, US", stars: 4, baseRate: 279, url: "https://www.ihg.com/kimpton/hotels/us/en/san-francisco/sfofw/hoteldetail", chain: "ihg", chainPropertyCode: "SFOFW", chainBrandCode: "KI" },
  // Los Angeles, CA
  { name: "Hotel Bel-Air", city: "Los Angeles", region: "California, US", stars: 5, baseRate: 899, url: "https://www.dorchestercollection.com/los-angeles/hotel-bel-air" },
  { name: "The Hollywood Roosevelt", city: "Los Angeles", region: "California, US", stars: 4, baseRate: 349, url: "https://www.thehollywoodroosevelt.com" },
  { name: "Shutters on the Beach", city: "Los Angeles", region: "California, US", stars: 5, baseRate: 699, url: "https://www.shuttersonthebeach.com" },
  { name: "Mama Shelter Los Angeles", city: "Los Angeles", region: "California, US", stars: 3, baseRate: 179, url: "https://www.mamashelter.com/los-angeles" },
  { name: "Freehand Los Angeles", city: "Los Angeles", region: "California, US", stars: 3, baseRate: 129, url: "https://freehandhotels.com/los-angeles" },
  // Miami, FL
  { name: "Faena Miami Beach", city: "Miami", region: "Florida, US", stars: 5, baseRate: 799, url: "https://www.faena.com/miami-beach" },
  { name: "The Setai Miami Beach", city: "Miami", region: "Florida, US", stars: 5, baseRate: 699, url: "https://www.thesetaihotel.com" },
  { name: "The Standard Spa Miami Beach", city: "Miami", region: "Florida, US", stars: 4, baseRate: 299, url: "https://www.standardhotels.com/miami/properties/miami-beach" },
  { name: "The Confidante", city: "Miami", region: "Florida, US", stars: 4, baseRate: 279, url: "https://www.theconfidantehotel.com" },
  { name: "Generator Miami", city: "Miami", region: "Florida, US", stars: 2, baseRate: 49, url: "https://staygenerator.com/hostels/miami" },
  // Nashville, TN
  { name: "The Hermitage Hotel", city: "Nashville", region: "Tennessee, US", stars: 5, baseRate: 449, url: "https://www.thehermitagehotel.com" },
  { name: "Noelle Nashville", city: "Nashville", region: "Tennessee, US", stars: 4, baseRate: 299, url: "https://www.noelle-nashville.com" },
  { name: "Graduate Nashville", city: "Nashville", region: "Tennessee, US", stars: 3, baseRate: 199, url: "https://www.graduatehotels.com/nashville" },
  { name: "Bobby Hotel", city: "Nashville", region: "Tennessee, US", stars: 4, baseRate: 279, url: "https://www.bobbyhotel.com" },
  { name: "Dream Nashville", city: "Nashville", region: "Tennessee, US", stars: 4, baseRate: 249, url: "https://www.dreamhotels.com/nashville" },
  // Maui, HI
  { name: "Four Seasons Maui", city: "Maui", region: "Hawaii, US", stars: 5, baseRate: 999, url: "https://www.fourseasons.com/maui" },
  { name: "Andaz Maui at Wailea", city: "Maui", region: "Hawaii, US", stars: 5, baseRate: 699, url: "https://www.hyatt.com/andaz/en-US/oggaw-andaz-maui-at-wailea-resort", chain: "hyatt", chainPropertyCode: "oggaw" },
  { name: "Hotel Wailea", city: "Maui", region: "Hawaii, US", stars: 5, baseRate: 599, url: "https://www.hotelwailea.com" },
  { name: "Hyatt Regency Maui", city: "Maui", region: "Hawaii, US", stars: 4, baseRate: 449, url: "https://www.hyatt.com/hyatt-regency/en-US/oggrm-hyatt-regency-maui-resort-and-spa", chain: "hyatt", chainPropertyCode: "oggrm" },
  { name: "Maui Seaside Hotel", city: "Maui", region: "Hawaii, US", stars: 3, baseRate: 179, url: "https://www.mauiseaside.com" },
  // Amsterdam, Netherlands
  { name: "Waldorf Astoria Amsterdam", city: "Amsterdam", region: "Netherlands", stars: 5, baseRate: 599, url: "https://www.hilton.com/en/hotels/amswawa-waldorf-astoria-amsterdam", chain: "hilton", chainPropertyCode: "AMSWAWA" },
  { name: "Pulitzer Amsterdam", city: "Amsterdam", region: "Netherlands", stars: 5, baseRate: 449, url: "https://www.pulitzeramsterdam.com" },
  { name: "Sir Adam Hotel", city: "Amsterdam", region: "Netherlands", stars: 4, baseRate: 229, url: "https://www.sirhotels.com/adam", chain: "sirhotels", chainPropertyCode: "67456", sirChainCode: "5154", sirConfig: "SBE_ADAM" },
  { name: "Hotel V Nesplein", city: "Amsterdam", region: "Netherlands", stars: 4, baseRate: 199, url: "https://www.hotelv.nl/nesplein" },
  { name: "ClinkNOORD", city: "Amsterdam", region: "Netherlands", stars: 2, baseRate: 49, url: "https://www.clinkhostels.com/amsterdam/clinknoord" },
  // Chicago, IL
  { name: "JW Marriott Chicago", city: "Chicago", region: "Illinois, US", stars: 5, baseRate: 399, url: "https://www.marriott.com/hotels/travel/chijw-jw-marriott-chicago", chain: "marriott", chainPropertyCode: "CHIJW" },
  { name: "Marriott Marquis Chicago", city: "Chicago", region: "Illinois, US", stars: 4, baseRate: 319, url: "https://www.marriott.com/hotels/travel/chimq-marriott-marquis-chicago", chain: "marriott", chainPropertyCode: "CHIMQ" },
  { name: "Hyatt Regency Chicago", city: "Chicago", region: "Illinois, US", stars: 4, baseRate: 279, url: "https://www.hyatt.com/hyatt-regency/en-US/chirc-hyatt-regency-chicago", chain: "hyatt", chainPropertyCode: "chirc" },
  { name: "Park Hyatt Chicago", city: "Chicago", region: "Illinois, US", stars: 5, baseRate: 449, url: "https://www.hyatt.com/park-hyatt/en-US/chiph-park-hyatt-chicago", chain: "hyatt", chainPropertyCode: "chiph" },
  { name: "InterContinental Chicago Magnificent Mile", city: "Chicago", region: "Illinois, US", stars: 4, baseRate: 359, url: "https://www.ihg.com/intercontinental/hotels/us/en/chicago/ordha/hoteldetail", chain: "ihg", chainPropertyCode: "ORDHA", chainBrandCode: "IC" },
  // Honolulu, HI
  { name: "Waikiki Beach Marriott Resort & Spa", city: "Honolulu", region: "Hawaii, US", stars: 4, baseRate: 399, url: "https://www.marriott.com/hotels/travel/hnlmc-waikiki-beach-marriott-resort-and-spa", chain: "marriott", chainPropertyCode: "HNLMC" },
  { name: "Sheraton Waikiki Beach Resort", city: "Honolulu", region: "Hawaii, US", stars: 4, baseRate: 349, url: "https://www.marriott.com/hotels/travel/hnlws-sheraton-waikiki-beach-resort", chain: "marriott", chainPropertyCode: "HNLWS" },
  { name: "The Royal Hawaiian, a Luxury Collection Resort", city: "Honolulu", region: "Hawaii, US", stars: 5, baseRate: 549, url: "https://www.marriott.com/hotels/travel/hnllc-the-royal-hawaiian-a-luxury-collection-resort-waikiki", chain: "marriott", chainPropertyCode: "HNLLC" },
  { name: "Hyatt Regency Waikiki Beach Resort & Spa", city: "Honolulu", region: "Hawaii, US", stars: 4, baseRate: 379, url: "https://www.hyatt.com/hyatt-regency/en-US/hnlrw-hyatt-regency-waikiki-beach-resort-and-spa", chain: "hyatt", chainPropertyCode: "hnlrw" },
  { name: "Moana Surfrider, A Westin Resort & Spa", city: "Honolulu", region: "Hawaii, US", stars: 4, baseRate: 429, url: "https://www.marriott.com/hotels/travel/hnlwi-moana-surfrider-a-westin-resort-and-spa-waikiki-beach", chain: "marriott", chainPropertyCode: "HNLWI" },
];
